[package]
name = "grond"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "grt"
path = "src/grt.rs"

[[bin]]
name = "gef"
path = "src/gef.rs"

[dependencies]
